import { I, btn, chip, tag, input, fld, cb, steps, chipTone, sk, fade, paper, letters, qsBar } from "./kit.js";
import { chartSvg, hist, lbT, filters } from "./parts-qs.js";

const title = (t) => `<div style="font:600 22px var(--font);color:var(--navy)">${t}</div>`;
const SUBJ = [["Accounting", "0452", "2027-2029"], ["ART And Design", "0400", "2028-2030"], ["Biology", "0610", "2026-2028"], ["Business Studies", "0450", "2026"], ["Chemistry", "0620", "2026-2028"], ["Computer Science", "0478", "2026-2028"], ["Economics", "0455", "2027-2029"], ["ESL", "0510", "2024-2026"]];
const TOPICS = ["The fundamentals of accounting", "Sources and recording of data", "Verification of accounting records", "Accounting procedures", "Preparation of financial statements"];
const TAGS = [["Completed", "", "check"], ["Revise", "sky", "rotate-ccw"], ["Memorised", "", "bookmark"], ["Doubt", "gold", "circle-alert"], ["Practice", "sky", "square-pen"], ["Critical", "coral", "flag"]];
const tagchips = (on = [], size = "") => TAGS.map(([t, c, ic]) => `<span class="tagchip ${c} ${on.includes(t) ? "on" : ""}" style="${size}">${I(ic, 13)}${t}</span>`).join("");
const sbar = (right = "", mid = "") => `<div class="bar1"><div class="brand"><b style="font-size:18px">Syllabus Digitizer</b><span class="tag" style="background:rgba(255,255,255,.18);color:var(--white)">Prototype</span></div>${mid}<div class="grow"></div>${right}</div>`;
const prog = (k = "on-dark") => btn("My progress & leaderboard", { k, i: "chart-line" });

/* ---------- S1 Shell + subject picker ---------- */
export const s1 = () => {
  const row = ([n, c, y], on) => `<div class="row" style="height:46px;padding:0 16px;gap:12px;border-bottom:1px solid var(--lb);${on ? "background:var(--navy);color:var(--white)" : "background:var(--white)"}"><b style="width:260px">${n}</b><span class="mono ${on ? "" : "mut"}" style="width:70px">${c}</span><span class="${on ? "" : "mut"}">${y}</span><div class="grow"></div>${I("chevron-right", 16)}</div>`;
  const a = sk("S1A", "Full-width subject list, filter in the bar", "no sidebar; list first, content after the pick", `${sbar(prog(), `<span style="margin-left:20px">${input("Filter subjects", { i: "search", s: "width:280px;background:var(--white)" })}</span>`)}<div class="body"><div class="grp" style="border-radius:4px 4px 0 0">IGCSE<span class="tag" style="background:var(--white)">31</span></div>${SUBJ.map((s, i) => row(s, i === 0)).join("")}</div>${fade}`, 460);
  const b = sk("S1B", "Subject dropdown in the bar", "searchable, A to Z, content opens straight under", `${sbar(prog(), `<span class="btn on-dark" style="height:36px;margin-left:20px;min-width:300px;justify-content:space-between"><span class="row" style="gap:8px">${I("book-open")}Accounting 0452 · 2027-2029</span>${I("chevron-down", 14)}</span>`)}
   <div class="menu" style="left:210px;top:54px;width:380px;padding:0"><div style="padding:8px;border-bottom:1px solid var(--lb)">${input("Filter subjects", { i: "search", s: "width:100%" })}</div>${SUBJ.map((s, i) => `<div class="${i === 0 ? "hl" : ""}"><b>${s[0]}</b><span class="mut mono" style="margin-left:auto">${s[1]}</span></div>`).join("")}</div>
   <div class="body" style="margin-top:0">${paper(200)}</div>`, 470);
  const c = sk("S1C", "Subject chips, collapse after pick", "chips wrap, no scroll", `${sbar(prog())}<div class="body"><div class="row" style="margin-bottom:12px">${title("IGCSE")}<span class="tag">31</span>${input("Filter subjects", { i: "search", s: "width:260px;margin-left:12px" })}</div><div class="row" style="gap:8px;flex-wrap:wrap">${SUBJ.concat(SUBJ.slice(0, 4).map((s) => [s[0] + " 2", "0" + (Number(s[1]) + 7), s[2]])).map(([n, c], i) => `<span class="tagchip ${i === 0 ? "on" : ""}" style="height:36px;padding:0 14px;font-size:13px">${n}<span class="mono" style="opacity:.7;font-weight:400">${c}</span></span>`).join("")}</div></div>`, 260);
  return { id: "s1", n: "S1", name: "Syllabus: header and subject list (Filter subjects, My progress & leaderboard)", html: a + b + c };
};

/* ---------- S2 Subject header + overview ---------- */
const hdrMeta = `<div class="row" style="gap:10px"><b style="font-size:22px;color:var(--navy)">Accounting</b><span class="mono mut">0452</span><span class="mut">exams 2027-2029</span><span class="tag">30 pages</span></div>`;
export const s2 = () => {
  const a = sk("S2A", "Header row, overview folded", "actions top right", `<div class="body"><div class="row">${hdrMeta}<div class="grow"></div>${btn("Export tagged topics", { i: "download" })}${btn("view raw JSON", { k: "gh", i: "braces" })}</div><div class="grp" style="margin-top:12px;border-radius:4px 4px 0 0">${I("chevron-right", 16)}Content overview</div></div>`, 160);
  const b = sk("S2B", "Sub-bar pinned under the top bar", "subject, actions and tag filter stay in view", `${sbar(prog())}<div class="row" style="height:52px;padding:0 24px;background:var(--white);border-bottom:1px solid var(--lb);gap:10px">${hdrMeta}<div class="grow"></div>${btn("Export tagged topics", { i: "download" })}${btn("view raw JSON", { k: "gh", i: "braces" })}</div><div class="body" style="margin-top:-18px;position:relative;z-index:0"><div class="surf" style="padding:14px">${paper(120)}</div></div>${fade}`, 300);
  const c = sk("S2C", "Tabs: Overview, Topics, Tagged", "actions beside the tabs", `<div class="body"><div class="row">${hdrMeta}</div><div class="row" style="margin-top:10px;border-bottom:1px solid var(--lb)"><div class="tabs" style="padding:0;border:0;background:transparent"><span>Overview</span><span class="on">Topics</span><span>Tagged</span></div><div class="grow"></div>${btn("Export tagged topics", { i: "download" })}${btn("view raw JSON", { k: "gh", i: "braces" })}</div></div>`, 150);
  return { id: "s2", n: "S2", name: "Subject header (Export tagged topics, view raw JSON, overview)", html: a + b + c };
};

/* ---------- S3 Topic rows and tags ---------- */
export const s3 = () => {
  const a = sk("S3A", "Title left, six tag chips wrap under it", "chips keep their colors, icons added", `<div class="body"><div class="surf" style="overflow:hidden">${TOPICS.slice(0, 4).map((t, i) => `<div style="padding:12px 16px;border-bottom:1px solid var(--lb)"><div class="row" style="gap:12px">${I("chevron-right", 16)}<b class="mono" style="width:24px">${i + 1}</b><b class="grow" style="font-size:15px">${t}</b></div><div class="row" style="gap:6px;margin:8px 0 0 52px;flex-wrap:wrap">${tagchips(i === 0 ? ["Completed", "Memorised"] : i === 2 ? ["Doubt"] : [])}</div></div>`).join("")}</div></div>`, 330);
  const b = sk("S3B", "One tag button, menu holds the six", "active tags show as dots on the row", `<div class="body" style="position:relative"><div class="surf" style="overflow:hidden">${TOPICS.slice(0, 4).map((t, i) => `<div class="row" style="height:52px;padding:0 16px;gap:12px;border-bottom:1px solid var(--lb)">${I("chevron-right", 16)}<b class="mono" style="width:24px">${i + 1}</b><b class="grow">${t}</b><span class="row" style="gap:4px">${i === 0 ? '<i style="width:10px;height:10px;border-radius:50%;background:var(--navy)"></i><i style="width:10px;height:10px;border-radius:50%;background:var(--navy);opacity:.5"></i>' : i === 2 ? '<i style="width:10px;height:10px;border-radius:50%;background:var(--gold)"></i>' : ""}</span>${btn("Tags", { c: "sm", i: "tag", is: 14 })}</div>`).join("")}</div>
   <div class="menu" style="right:40px;top:110px;width:230px">${TAGS.map(([t, c, ic], i) => `<div class="${i === 0 ? "hl" : ""}">${cb(i === 0 || i === 2)}${I(ic, 16)}${t}</div>`).join("")}</div></div>`, 390);
  const c = sk("S3C", "Completed toggle, other tags in a popover", "the common action is one tap", `<div class="body"><div class="surf" style="overflow:hidden">${TOPICS.slice(0, 4).map((t, i) => `<div class="row" style="height:52px;padding:0 16px;gap:12px;border-bottom:1px solid var(--lb)">${I("chevron-right", 16)}<b class="mono" style="width:24px">${i + 1}</b><b class="grow">${t}</b>${i === 2 ? `<span class="tagchip gold on">${I("circle-alert", 13)}Doubt</span>` : ""}<span class="tagchip ${i === 0 ? "on" : ""}" style="height:30px;padding:0 12px">${I("check", 14)}Completed</span>${btn("More tags", { c: "sm", i: "ellipsis", is: 14 })}</div>`).join("")}</div></div>`, 290);
  return { id: "s3", n: "S3", name: "Topic rows and tags (Completed, Revise, Memorised, Doubt, Practice, Critical)", html: a + b + c };
};

/* ---------- S4 Expanded topic ---------- */
export const s4 = () => {
  const head = (open) => `<div class="row" style="height:52px;padding:0 16px;gap:12px;background:var(--white);border-bottom:1px solid var(--lb)">${I(open ? "chevron-down" : "chevron-right", 16)}<b class="mono" style="width:24px">2</b><b class="grow">Sources and recording of data</b>${tagchips(["Revise"], "height:24px")}</div>`;
  const a = sk("S4A", "Opens in place, image full width", "sub-topics listed under the image", `<div class="body"><div class="surf" style="overflow:hidden">${head(1)}<div style="padding:14px 16px;background:var(--off)">${paper(190)}<div class="row" style="margin-top:10px;gap:8px">${["2.1 The double entry system", "2.2 Business documents", "2.3 Books of prime entry"].map((t) => `<span class="tagchip" style="height:30px">${t}</span>`).join("")}</div></div>${TOPICS.slice(2, 4).map((t, i) => `<div class="row" style="height:52px;padding:0 16px;gap:12px;border-bottom:1px solid var(--lb);background:var(--white)">${I("chevron-right", 16)}<b class="mono" style="width:24px">${i + 3}</b><b>${t}</b></div>`).join("")}</div></div>`, 440);
  const b = sk("S4B", "Image opens in a bottom sheet", "list stays visible above", `<div class="body"><div class="surf" style="overflow:hidden">${head(0)}${TOPICS.slice(2, 5).map((t, i) => `<div class="row" style="height:52px;padding:0 16px;gap:12px;border-bottom:1px solid var(--lb);background:var(--white)">${I("chevron-right", 16)}<b class="mono" style="width:24px">${i + 3}</b><b>${t}</b></div>`).join("")}</div></div><div class="dimmer"></div><div class="sheet" style="top:130px"><div class="grip"></div><div class="row" style="padding:2px 24px 10px"><b style="font-size:18px">2 Sources and recording of data</b><div class="grow"></div>${tagchips(["Revise"], "height:24px")}${btn("", { c: "ic", i: "x" })}</div><div style="padding:0 24px 16px">${paper(240)}</div></div>`, 470);
  const c = sk("S4C", "Thumbnail in the row, full view on tap", "preview keeps scanning fast", `<div class="body"><div class="surf" style="overflow:hidden">${TOPICS.slice(0, 4).map((t, i) => `<div class="row" style="height:84px;padding:0 16px;gap:14px;border-bottom:1px solid var(--lb)"><div style="width:110px;height:60px">${paper(60)}</div><div class="grow"><b class="mono mut">${i + 1}</b> <b style="font-size:15px">${t}</b><div class="row" style="gap:6px;margin-top:6px">${tagchips(i === 1 ? ["Revise"] : [], "height:22px;font-size:11px")}</div></div>${btn("Open", { c: "sm", i: "eye", is: 14 })}</div>`).join("")}</div></div>`, 400);
  return { id: "s4", n: "S4", name: "Expanded topic (image, sub-topics, tags)", html: a + b + c };
};

/* ---------- S5 Syllabus progress ---------- */
const tHist = `<table class="tbl"><colgroup><col><col style="width:160px"><col style="width:150px"><col style="width:130px"></colgroup><thead><tr><th>Topic</th><th>Subject</th><th>Chapter</th><th>When</th></tr></thead><tbody>${[["2.1 The double entry system", "Accounting", "2", "Sep 29"], ["1.2 The accounting equation", "Accounting", "1", "Sep 27"], ["4.1 Capital and revenue", "Accounting", "4", "Sep 25"]].map((r) => `<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join("")}</tbody></table>`;
const tLb = lbT.replace("Average %", "Topics completed").replace("Total correct", "Subjects").replace(/>91</, ">46<").replace(/>88</, ">41<").replace(/>84</, ">37<");
export const s5 = () => {
  const a = sk("S5A", "One column: chart, history, leaderboard", "Back to syllabus in the bar", `${sbar(btn("Back to syllabus", { k: "on-dark", i: "chevron-left" }))}<div class="body"><div class="row" style="margin-bottom:10px">${title("Topics completed over time")}<div class="grow"></div>${filters}</div>${chartSvg(1232, 150)}<div style="margin-top:12px">${tHist}</div></div>${fade}`, 440);
  const b = sk("S5B", "Tabs: Progress, History, Leaderboard", "one section at a time", `${sbar(btn("Back to syllabus", { k: "on-dark", i: "chevron-left" }))}<div class="body"><div class="row" style="margin-bottom:10px"><span class="seg"><span class="on">Progress</span><span>History</span><span>Leaderboard</span></span><div class="grow"></div>${filters}</div>${chartSvg(1232, 210)}</div>`, 400);
  const c = sk("S5C", "Summary strip, sections fold", "counts first", `${sbar(btn("Back to syllabus", { k: "on-dark", i: "chevron-left" }))}<div class="body"><div class="row" style="gap:12px;margin-bottom:12px">${[["Completed", "46"], ["Revise", "12"], ["Doubt", "5"], ["Rank", "2"]].map(([l, v]) => `<div class="surf grow" style="padding:10px 14px"><div class="lbl">${l}</div><b style="font-size:24px">${v}</b></div>`).join("")}</div><div class="grp">${I("chevron-down", 16)}Topics completed over time</div><div style="padding:10px 0">${chartSvg(1232, 120)}</div><div class="grp">${I("chevron-right", 16)}Completion history</div><div class="grp" style="margin-top:1px">${I("chevron-right", 16)}Leaderboard</div></div>`, 420);
  return { id: "s5", n: "S5", name: "Syllabus progress and leaderboard", html: a + b + c };
};

/* ---------- Phones ---------- */
const phone = (inner, h = 844) => `<div class="wrap" style="width:390px;flex:none"><div class="sk ph" style="height:${h}px">${inner}</div></div>`;
const phCap = (id, t, n) => `<div style="width:390px;flex:none"><div class="cap" style="margin:0 0 8px"><code>${id}</code>${t}</div><div class="mut" style="font-size:14px;margin:-4px 0 8px">${n}</div></div>`;
const phBar = (t, r = "") => `<div class="bar1" style="height:52px;padding:0 12px;gap:8px"><b style="font-size:16px" class="grow tr">${t}</b>${r}</div>`;
const phoneRow = (k, sel) => `<div class="surf" style="padding:10px 12px;margin-bottom:8px"><div class="row"><b>${k}</b><div class="grow"></div>${sel}</div></div>`;
export const q13 = () => {
  const a = phone(`${phBar("DC Question Solver", btn("", { k: "on-dark", c: "ic", i: "chart-line" }))}<div style="padding:12px 14px;background:var(--off)">${["Board|A Levels", "Subject|Physics", "Component|Paper 1: Multiple Choice", "Paper Type|Yearly past papers", "Year|2026", "Session|Feb/March", "Paper|Paper 12"].map((s) => { const [k, v] = s.split("|"); return fld(k, v, { dd: 1, v: 1, s: "margin-bottom:10px" }); }).join("")}${btn("Mistakes Mode", { i: "rotate-ccw", s: "width:100%;justify-content:center;height:40px" })}<div style="height:8px"></div>${btn("Upload your own QP + MS PDFs", { i: "upload", s: "width:100%;justify-content:center;height:40px" })}</div><div class="row" style="position:absolute;left:0;right:0;bottom:0;height:64px;padding:0 14px;background:var(--white);border-top:1px solid var(--lb)">${btn("Fetch this paper and start", { k: "pri", s: "width:100%;height:44px;justify-content:center;font-size:15px" })}</div>`);
  const b = phone(`${phBar("Test", `<span class="row" style="gap:6px;font:600 15px var(--mono)">${I("timer", 16)}05:12</span>`)}<div style="padding:12px 14px;background:var(--off)"><div class="surf" style="padding:12px"><div class="row" style="margin-bottom:8px"><b>Question 3</b><div class="grow"></div>${btn("Flag", { c: "sm", i: "flag", is: 14 })}</div>${paper(230)}<div class="row" style="margin-top:10px;gap:6px;justify-content:space-between">${letters("C")}</div><div style="margin-top:10px">${btn("Check answer", { i: "circle-check", s: "width:100%;justify-content:center;height:40px" })}</div></div></div><div class="row" style="position:absolute;left:0;right:0;bottom:0;height:64px;padding:0 12px;background:var(--navy);gap:8px">${btn("Pause", { k: "on-dark", i: "pause" })}${btn("Cancel", { k: "on-dark", i: "x" })}<div class="grow"></div>${btn("Submit quiz", { k: "pri", s: "height:40px;padding:0 16px" })}</div>`);
  const c = phone(`${phBar("Results", btn("", { k: "on-dark", c: "ic", i: "chart-line" }))}<div style="padding:14px;background:var(--off)"><div class="row" style="gap:10px;margin-bottom:12px"><b style="font-size:32px">31 / 38</b><span class="tag">82%</span>${chip("Saved", "ok")}</div><div class="row" style="gap:6px;flex-wrap:wrap">${Array.from({ length: 38 }, (_, i) => `<span class="qn ${[1, 4, 11, 19, 27, 30, 33].includes(i) ? "bad" : i === 2 ? "warn" : ""}">${i + 1}</span>`).join("")}</div></div><div class="row" style="position:absolute;left:0;right:0;bottom:0;height:64px;padding:0 14px;background:var(--white);border-top:1px solid var(--lb)">${btn("Digitize another paper", { k: "pri", s: "width:100%;height:44px;justify-content:center;font-size:15px" })}</div>`);
  const html = `<div style="display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap"><div>${phCap("Q13A", "Picker, fetch pinned at bottom", "seven selects stacked")}${a}</div><div>${phCap("Q13B", "Quiz, bar pinned at bottom", "timer top, actions bottom")}${b}</div><div>${phCap("Q13C", "Results, number grid", "Digitize another paper pinned")}${c}</div></div>`;
  return { id: "q13", n: "Q13", name: "Question Solver on a phone (390 × 844)", html, raw: true };
};
export const s13 = () => {
  const a = phone(`${phBar("Syllabus Digitizer", btn("", { k: "on-dark", c: "ic", i: "chart-line" }))}<div style="padding:10px 14px;background:var(--off)">${input("Filter subjects", { i: "search", s: "width:100%" })}</div>${SUBJ.concat(SUBJ).map(([n, c], i) => `<div class="row" style="height:52px;padding:0 14px;gap:10px;background:var(--white);border-bottom:1px solid var(--lb)"><b class="grow tr">${n}</b><span class="mono mut">${c}</span>${I("chevron-right", 16)}</div>`).join("")}`);
  const b = phone(`${phBar("Accounting 0452", btn("", { k: "on-dark", c: "ic", i: "ellipsis" }))}<div style="padding:10px 14px;background:var(--off)">${TOPICS.slice(0, 5).map((t, i) => `<div class="surf" style="padding:10px 12px;margin-bottom:8px"><div class="row" style="gap:10px"><b class="mono">${i + 1}</b><b class="grow">${t}</b>${btn("Tags", { c: "sm", i: "tag", is: 14 })}</div></div>`).join("")}</div>
   <div class="sheet" style="top:420px"><div class="grip"></div><div style="padding:0 14px 14px"><b style="font-size:16px">2 Sources and recording of data</b><div style="margin-top:10px">${TAGS.map(([t, c, ic], i) => `<div class="row" style="height:46px;gap:12px;border-bottom:1px solid var(--lb)">${cb(i === 1)}${I(ic, 18)}${t}</div>`).join("")}</div></div></div>`);
  const c = phone(`${phBar("Progress", btn("", { k: "on-dark", c: "ic", i: "chevron-left" }))}<div style="padding:12px 14px;background:var(--off)"><span class="seg" style="width:100%"><span class="on" style="flex:1;justify-content:center">Progress</span><span style="flex:1;justify-content:center">History</span><span style="flex:1;justify-content:center">Leaderboard</span></span><div style="margin-top:12px">${chartSvg(360, 190)}</div><div class="row" style="gap:8px;margin-top:12px">${[["Completed", "46"], ["Doubt", "5"]].map(([l, v]) => `<div class="surf grow" style="padding:10px 12px"><div class="lbl">${l}</div><b style="font-size:22px">${v}</b></div>`).join("")}</div></div>`);
  const html = `<div style="display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap"><div>${phCap("S13A", "Subject list, filter on top", "full-width rows")}${a}</div><div>${phCap("S13B", "Topic cards, tag sheet", "six tags as checkbox rows")}${b}</div><div>${phCap("S13C", "Progress with segments", "chart, counts")}${c}</div></div>`;
  return { id: "s13", n: "S13", name: "Syllabus Viewer on a phone (390 × 844)", html, raw: true };
};
