// Coverage of the classic manifest by the new UI (planning/new-ui-migration-plan.md 4.1).
//   node ui2/testing/parity-report.mjs            prints coverage per classic file, writes planning/parity/SUMMARY.md
//   node ui2/testing/parity-report.mjs --strict   exits 1 unless every control is mapped (used at phase exit)
// planning/parity/mapping.json maps a control id to { status, to, reason }.
// status: "mapped" (the new UI has it), "merged" or "moved" (reason required), "dropped" (reason and user sign-off required).
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DIR = path.join(root, "planning/parity");
const STATUSES = new Set(["mapped", "merged", "moved", "dropped"]);

export function loadManifests(dir = DIR) {
  return fs.readdirSync(dir).filter((f) => /^classic-.*\.json$/.test(f)).sort().map((f) => ({ name: f, ...JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")) }));
}

export function loadMapping(dir = DIR) {
  const p = path.join(dir, "mapping.json");
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : {};
}

/** Pure: coverage numbers for manifests against a mapping. */
export function coverage(manifests, mapping) {
  const problems = [];
  const files = manifests.map((m) => {
    let mapped = 0;
    const missing = [];
    for (const c of m.controls) {
      const e = mapping[c.id];
      if (!e) {
        missing.push(c.id);
        continue;
      }
      if (!STATUSES.has(e.status)) problems.push(`${c.id}: unknown status "${e.status}"`);
      else if (e.status !== "mapped" && !e.reason) problems.push(`${c.id}: status ${e.status} needs a reason`);
      else if (e.status === "dropped" && !e.signedOff) problems.push(`${c.id}: dropped needs signedOff: true (the user approves every drop)`);
      else mapped++;
    }
    return { file: m.file, controls: m.controls.length, mapped, missing };
  });
  const known = new Set(manifests.flatMap((m) => m.controls.map((c) => c.id)));
  const stale = Object.keys(mapping).filter((id) => !known.has(id));
  const total = files.reduce((a, f) => a + f.controls, 0);
  const done = files.reduce((a, f) => a + f.mapped, 0);
  return { files, total, done, percent: total ? Math.round((1000 * done) / total) / 10 : 100, problems, stale };
}

export function summaryMarkdown(manifests, cov) {
  const lines = ["# Classic UI parity manifest summary", "", "Generated by `ui2/testing/parity-report.mjs`. Do not edit by hand.", "", `Controls: **${cov.total}**, mapped: **${cov.done}** (${cov.percent}%).`, "", "| Classic file | Controls | API calls | Mapped |", "|---|---|---|---|"];
  for (const m of manifests) {
    const f = cov.files.find((x) => x.file === m.file);
    lines.push(`| \`${m.file}\` | ${m.counts.controls} | ${m.counts.apiCalls} | ${f.mapped} |`);
  }
  const mgmt = manifests.find((m) => m.file === "app/dashboard/management/page.js");
  if (mgmt) {
    const per = {};
    for (const c of mgmt.controls) per[c.component] = (per[c.component] || 0) + 1;
    lines.push("", "## Management dashboard, controls per component", "", "| Component | Controls |", "|---|---|");
    for (const [k, v] of Object.entries(per).sort((a, b) => b[1] - a[1])) lines.push(`| ${k} | ${v} |`);
  }
  return lines.join("\n") + "\n";
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const manifests = loadManifests();
  const cov = coverage(manifests, loadMapping());
  for (const f of cov.files) console.log(`${String(f.mapped).padStart(4)}/${String(f.controls).padEnd(4)} ${f.file}`);
  console.log(`\nparity: ${cov.done}/${cov.total} controls mapped (${cov.percent}%)`);
  for (const p of cov.problems) console.log("PROBLEM", p);
  for (const s of cov.stale) console.log("STALE mapping entry (control no longer exists in classic):", s);
  fs.writeFileSync(path.join(DIR, "SUMMARY.md"), summaryMarkdown(manifests, cov));
  if (process.argv.includes("--strict") && (cov.done !== cov.total || cov.problems.length)) process.exit(1);
}
