// Real ITU-T E.164 country calling codes — stable public reference data,
// not a claim that needs live verification the way a business stat would.
// Grouped the same way lib/timezones.js groups TIMEZONE_GROUPS (a
// "Common" set for this school's actual markets -- UK, India, Saudi,
// Pakistan, UAE -- first, everything else alphabetical after), so any
// dropdown built from this looks and behaves consistently with the
// existing timezone picker.

const COMMON = [
  { dial: "+44", name: "UK" },
  { dial: "+91", name: "India" },
  { dial: "+966", name: "Saudi Arabia" },
  { dial: "+92", name: "Pakistan" },
  { dial: "+971", name: "UAE" },
];
const ALL = [
  { dial: "+93", name: "Afghanistan" },
  { dial: "+355", name: "Albania" },
  { dial: "+213", name: "Algeria" },
  { dial: "+54", name: "Argentina" },
  { dial: "+61", name: "Australia" },
  { dial: "+43", name: "Austria" },
  { dial: "+880", name: "Bangladesh" },
  { dial: "+32", name: "Belgium" },
  { dial: "+55", name: "Brazil" },
  { dial: "+673", name: "Brunei" },
  { dial: "+1", name: "Canada" },
  { dial: "+86", name: "China" },
  { dial: "+57", name: "Colombia" },
  { dial: "+20", name: "Egypt" },
  { dial: "+358", name: "Finland" },
  { dial: "+33", name: "France" },
  { dial: "+49", name: "Germany" },
  { dial: "+30", name: "Greece" },
  { dial: "+852", name: "Hong Kong" },
  { dial: "+36", name: "Hungary" },
  { dial: "+62", name: "Indonesia" },
  { dial: "+98", name: "Iran" },
  { dial: "+964", name: "Iraq" },
  { dial: "+353", name: "Ireland" },
  { dial: "+972", name: "Israel" },
  { dial: "+39", name: "Italy" },
  { dial: "+81", name: "Japan" },
  { dial: "+962", name: "Jordan" },
  { dial: "+254", name: "Kenya" },
  { dial: "+965", name: "Kuwait" },
  { dial: "+961", name: "Lebanon" },
  { dial: "+218", name: "Libya" },
  { dial: "+60", name: "Malaysia" },
  { dial: "+960", name: "Maldives" },
  { dial: "+52", name: "Mexico" },
  { dial: "+212", name: "Morocco" },
  { dial: "+977", name: "Nepal" },
  { dial: "+31", name: "Netherlands" },
  { dial: "+64", name: "New Zealand" },
  { dial: "+234", name: "Nigeria" },
  { dial: "+47", name: "Norway" },
  { dial: "+968", name: "Oman" },
  { dial: "+63", name: "Philippines" },
  { dial: "+48", name: "Poland" },
  { dial: "+351", name: "Portugal" },
  { dial: "+974", name: "Qatar" },
  { dial: "+40", name: "Romania" },
  { dial: "+7", name: "Russia" },
  { dial: "+65", name: "Singapore" },
  { dial: "+27", name: "South Africa" },
  { dial: "+82", name: "South Korea" },
  { dial: "+34", name: "Spain" },
  { dial: "+94", name: "Sri Lanka" },
  { dial: "+46", name: "Sweden" },
  { dial: "+41", name: "Switzerland" },
  { dial: "+886", name: "Taiwan" },
  { dial: "+66", name: "Thailand" },
  { dial: "+216", name: "Tunisia" },
  { dial: "+90", name: "Turkey" },
  { dial: "+256", name: "Uganda" },
  { dial: "+380", name: "Ukraine" },
  { dial: "+1", name: "USA" },
  { dial: "+998", name: "Uzbekistan" },
  { dial: "+84", name: "Vietnam" },
  { dial: "+967", name: "Yemen" },
].sort((a, b) => a.name.localeCompare(b.name));

export const COUNTRY_CODE_GROUPS = [
  { label: "Common", options: COMMON },
  { label: "All countries", options: ALL },
];

export const DEFAULT_COUNTRY_DIAL = "+91";
