// Writes ui2/styles/tokens.css from ui2/styles/palette.mjs. Run: node scripts/build-tokens.mjs
// `--check` exits 1 if the committed file differs (used by the tests, so the CSS can never drift).
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { TOKENS } from "../ui2/styles/palette.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = path.join(root, "ui2/styles/tokens.css");

export function buildTokensCss() {
  const lines = Object.entries(TOKENS).map(([k, v]) => `  --u2-${k}: ${v};`);
  return `/* GENERATED by scripts/build-tokens.mjs from ui2/styles/palette.mjs. Do not edit by hand. */\n.u2, .u2-portal {\n${lines.join("\n")}\n}\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const css = buildTokensCss();
  if (process.argv.includes("--check")) {
    const same = fs.existsSync(out) && fs.readFileSync(out, "utf8") === css;
    if (!same) {
      console.error("ui2/styles/tokens.css is out of date. Run: node scripts/build-tokens.mjs");
      process.exit(1);
    }
    console.log("tokens.css is up to date");
  } else {
    fs.writeFileSync(out, css);
    console.log("wrote", path.relative(root, out), `(${Object.keys(TOKENS).length} tokens)`);
  }
}
